version: '2.0'

services:
  dump978:
    image: ${UAT978_CONTAINER}
    tty: true
    container_name: dump978
    hostname: dump978
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - TZ=${FEEDER_TZ}
      - LAT=${FEEDER_LAT}
      - LON=${FEEDER_LONG}
      - DUMP978_RTLSDR_DEVICE=${FEEDER_SERIAL_978}
      - DUMP978_SDR_GAIN=${UAT_SDR_GAIN}
      - DUMP978_SDR_PPM=${UAT_SDR_PPM}
      - AUTOGAIN_INITIAL_PERIOD=7200
    volumes:
      - /opt/adsb/config/dump978/autogain:/run/autogain
      - /dev:/dev:ro
    ports:
      - 9780:80
    tmpfs:
      - /run/readsb
